# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
