# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170324_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(),
        ),
    ]
