# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170325_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(),
        ),
    ]
